### ISSUE TITLE
callshift.bat fails with some arguments

### ISSUE THREAD

**Issue by jeb-de** [andry81/contools#2]
It fails with `callshift.bat 0 echo "b=%b ~b=%~b"`

The output is:
`"b=1 ~b=1"`

The expected output is:
`"b=%b ~b=%~b"`

And 
`callshift.bat 0 echo "This %~$ strange text is invisble %var%  a:b"` 
Outputs:
`"This "`

The problem is in the block:
```
for %%i in (1) do (
  set "PROMPT=$_"
  echo on
  for %%b in (1) do rem * %*#
  @echo off
) > "%CMDLINE_TEMP_FILE%"
```

If `%*` contains `%i` or `%b`, it expands to `1`.
to `FOR %%1 in (1) do` itself is superfluous, it can be deleted.

The `FOR %%b in (1) do` should be modified to `FOR %%b in (%%b) do`.
That would expand a simple `hello %b` to `hello %b`, but still would fail with `hello %~b %~fb`.
This can be solved by using `setlocal DisableExtensions`, as it disables the `%~ expressions at all

Then the block becomes
```
(
  setlocal DisableExtensions
  (set PROMPT=$_)
  echo on
  for %%b in (%%b) do rem * %*#
  @echo off
  endlocal
) > "%CMDLINE_TEMP_FILE%"

```

**Comment by andry81** [comment]
Fixed in e1c2bd4ac366c49acebaacadf388c5dd9e634805
