### ISSUE TITLE
Batch FOR-Loops EOL relies on a rare character

### ISSUE THREAD

**Issue by jeb-de** [andry81/contools#3]
In many batch files is a for-loop used like this

`FOR /F "EOL=<rare-character> tokens=* delims="` 

It's used to fetch a full line and avoid skipping of lines, when they begin with the EOL character.

But using a rare-character has some drawbacks
- Code can not be copied to many forums (Like stackoverflow, Dostips, ...) because these characters are stripped
- Some editors can not handle theses characters well
- A real line/string can still start with such a character

All points can be solved by using an empty EOL character.
To create such a FOR-loop, quoting must not be used

`FOR /F tokens^=*^ delims^=#^ EOL^=  %%L in (somefile) do echo ...%%L`

Or when a string used, it can be even more simplified by enclosing the string in quotes and remove them later by using the `%%~` syntax.

`FOR /F "delims="   %%L in (""!string!"") do echo ...%%~L`

Btw. `"tokens=* delims="` can be simplified to `"delims="`

**Comment by andry81** [comment]
> FOR /F "delims=" %%L in (""!string!"") do echo ...%%~L

What the difference with this:

```bat
FOR /F "delims=" %%L in ("!string!") do echo ...%%L
```

**Comment by jeb-de** [comment]
This sample shows the difference:

```
@echo off
setlocal EnableDelayedExpansion
SET "string=;Hello"
FOR /F "delims=" %%L in ("!string!") do echo FAIL: %%L
FOR /F "delims=" %%L in (""!string!"") do echo WORK: %%~L
```

Only the second FOR works, because the string always begins with a quote.
Therefore there can never a problem with the EOL character.
And the loop even works for empty strings, because they are enclosed in quotes

**Comment by andry81** [comment]
> FOR /F tokens^=*^ delims^=#^ EOL^= %%L in (somefile) do echo ...%%L

I think you can shorten that to this:

```bat
FOR /F "tokens=* delims=#"^ EOL^= %%L in (somefile) do echo ...%%L
```

**Comment by jeb-de** [comment]
> I think you can shorten that to this:
> `FOR /F "tokens=* delims=#"^ EOL^= %%L in (somefile) do echo ...%%L`

Yes, that works too and is even a bit simpler

**Comment by andry81** [comment]
> Only the second FOR works, because the string always begins with a quote.

Yes, by default the `;` is a quote character, so you can redefine it to empty:

```bat
FOR /F "delims="^ EOL^= %%L in ("!string!") do echo FAIL: %%L
```

> And the loop even works for empty strings, because they are enclosed in quotes

Interesting, but must be tested on all Windows versions. Not sure it is stable.

**Comment by jeb-de** [comment]
> Interesting, but must be tested on all Windows versions. Not sure it is stable.

I am quite sure that this already worked in XP.
This is only another way to solve the EOL problem, for me it looks a bit better than the empty EOL variant and in some situations it is convenient that it can handle empty strings.

**Comment by andry81** [comment]
> for me it looks a bit better than the empty EOL variant

It has an issue :smile: 

```bat
@echo off
setlocal
set string=!
setlocal ENABLEDELAYEDEXPANSION
FOR /F "delims=" %%L in (""!string!"") do echo WORK: %%~L?
```

**Comment by jeb-de** [comment]
Not really  😄
The exclamation mark only disappears just after the expansion in "WORK: %%~L",  because delayed expansion was active.
For-Meta-variables always have this problem, because of the order of expansions.

```
@echo off
setlocal DisableDelayedExpansion
set string=!
setlocal ENABLEDELAYEDEXPANSION
FOR /F "delims=" %%L in (""!string!"") do (
    endlocal
    echo WORK: %%~L?
)
```

**Comment by andry81** [comment]
How about the case with a file read? You still have to use the empty EOL.

**Comment by andry81** [comment]
I've tested the `""!string!""` on XP/7/8, x86/x64. Seems works the same way for all 256 characters.

**Comment by andry81** [comment]
> I think you can shorten that to this:
> 
> ```batchfile
> FOR /F "tokens=* delims=#"^ EOL^= %%L in (somefile) do echo ...%%L
> ```

Or even shorter :)

```batchfile
FOR /F "tokens=* delims=#"EOL^= %%L in (somefile) do echo ...%%L
```

**Comment by andry81** [comment]
> FOR /F "delims=" %%L in (""!string!"") do echo ...%%~L

Found the case where it does not work as expected:

```
FOR /F "delims=" %%L in (""!string:* =!"") do echo ...%%~L
```

, where you want to remove everything before the last space and the string can be empty before or after.

**Comment by andry81** [comment]
> ```batchfile
> FOR /F "delims=" %%L in (""!string:* =!"") do echo ...%%~L
> ```

Workaround:

```bat
FOR /F "usebackq delims=" %%L in ('"!string:* =!"') do echo ...%%~L
```
